### ISSUE TITLE
Extract ZopeResourceTreeTraversal from nti.appserver.traversal

### ISSUE THREAD

**Issue by cutz** [NextThought/nti.app.pyramid_zope#2]
The [ZopeResourceTreeTraversal code](https://github.com/NextThought/nti.dataserver/blob/48c23547c9d00276af2758dd420113694247ecbb/src/nti/appserver/traversal.py#L74) from nti.dataserver seems like a good candidate to extract in to this repository.

This traversal mechanism would be useful in other projects. Looking at the imports from that file it looks fairly isolated. Any reason we should not do this?

**Comment by jamadden** [comment]
👍 That seems like a good idea to me. 

That's really old code, so it's probably also a good idea to see if the comments still hold. The pyramid implementation may have been refactored and/or there may be better hooks now.

**Comment by cutz** [comment]
I looked briefly at the history for the pyramid implementation yesterday and besides some formatting changes not much has changed. The implementation still dates back to what we appear to have based our subclass on. I'll do a closer diff and open a PR.

**Comment by jamadden** [comment]
For this and #5 it's probably worth making some effort to [save the history](https://stackoverflow.com/questions/44777043/git-copy-history-of-file-from-one-repository-to-another) of those files.
