### ISSUE TITLE
Extract ZopeTranslationDirectories

### ISSUE THREAD

**Issue by jamadden** [NextThought/nti.app.pyramid_zope#5]
From [nti.dataserver:nti/app/i18n/adapters.py](https://github.com/NextThought/nti.dataserver/blob/48c23547c9d00276af2758dd420113694247ecbb/src/nti/app/i18n/adapters.py#L157). It's come up for a different project now.

In fact, probably much of that entire package could be moved here.

**Comment by jamadden** [comment]
Besides `adapters.py`, the code in `subscribers.py` and `interfaces.py` also make sense to move.  I'm a bit torn, though, on whether it is best moved here or to its own distribution and package.

The pros of moving it here are that it keeps vaguely-related code together (in the sense that it all bridges Pyramid and Zope layers), it has the least project-management overhead, and it doesn't require inventing a new distribution name.

The cons of moving it here and the pros of moving it to a new distribution are that it may expand to include more things in the future, making that a better choice and sparing another move (though that code hasn't changed in a few years and I'm not sure what the expanse would be). But another con of a new distribution is that the obvious name, `nti.app.i18n`, would conflict with the legacy location, where a `views.py` needs to remain.

On the whole, I'm leaning towards moving it here as being sufficient. Say something if you feel otherwise.

**Comment by cutz** [comment]
> But another con of a new distribution is that the obvious name, nti.app.i18n, would conflict with the legacy location, where a views.py needs to remain.

Are we sure the view is actually still relevant and used?

**Comment by jamadden** [comment]
> Are we sure the view is actually still relevant and used?

No idea 😄 . The route is still registered, and some resource files do exist, but I haven't tried to look and see if the URL (`${environment:webapp_location}resources/strings/strings.js`) is ever hit.

**Comment by cutz** [comment]
It's still relevant to some of our legacy stuff.

**Comment by jamadden** [comment]
These have a dependency on the (private) interaface `IUser` and function `get_remote_user(request)`. 

I am refactoring that to be based on `zope.security` using `IInteraction`, `IParticipation` and `IPrincipal`. Because of our (private) `zope_security_interaction_tween` that sets the current `IInteraction` to have a single `IParticipation` of the current `IUser` (or the `IUnauthenticatedPrincipal`) everything should Just Work.

However, that suggests that `zope_security_interaction_tween` should move here.

**Comment by cutz** [comment]
Makes sense. The tween uses some internal interfaces and classes as well so we may need to user or provide a different layer of abstraction there.

**Comment by jamadden** [comment]
> The tween uses some internal interfaces and classes as well so we may need to user or provide a different layer of abstraction there.

Agreed. The block of code you're talking about (getting from `request.authenticated_userid` to an `IUser` and eventually `IPrincipal`) can be generically replaced with `zope.authentication.interfaces.IAuthentication.getPrincipal(id)`.

Alternately, there may be something else on the Pyramid request we could/should use. I'd have to revisit that part of our stack to be sure. However, I'd prefer to continue to spread the use of `zope.authentication` since its designed with multiple sites, overlapping login names, and a distinction between login names and principal ids in mind.
